# Apps
bind = SUPER, A, exec, kitty
bind = SUPER, E, exec, /home/htech/scripts/pcmanfm.sh
bind = SUPER, B, exec, firefox
bind = SUPER, M, exec, cider
bind = SUPER, SPACE, exec, rofi -show drun

# Window management
bind = SUPER, Q, killactive
bind = SUPER, F, fullscreen
bind = SUPER, T, togglefloating
bind = SUPER, P, pseudo
bind = SUPER, J, togglesplit

# Focus
bind = SUPER, left,  movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up,    movefocus, u
bind = SUPER, down,  movefocus, d

# Move windows
bind = SUPER CTRL, left,  movewindow, l
bind = SUPER CTRL, right, movewindow, r
bind = SUPER CTRL, up,    movewindow, u
bind = SUPER CTRL, down,  movewindow, d
bind = SUPER CTRL, Next, movetoworkspace, e+1
bind = SUPER CTRL, Prior,  movetoworkspace, e-1

# Resize
binde = SUPER,      equal, resizeactive,  50  0
binde = SUPER,      minus, resizeactive, -50  0
binde = SUPER CTRL, equal, resizeactive,  0  -50
binde = SUPER CTRL, minus, resizeactive,  0   50

# Workspaces - switch
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10
bind = SUPER, Next, workspace, e+1
bind = SUPER, Prior,  workspace, e-1

# Workspaces - move window to
bind = SUPER CTRL, 1, movetoworkspace, 1
bind = SUPER CTRL, 2, movetoworkspace, 2
bind = SUPER CTRL, 3, movetoworkspace, 3
bind = SUPER CTRL, 4, movetoworkspace, 4
bind = SUPER CTRL, 5, movetoworkspace, 5
bind = SUPER CTRL, 6, movetoworkspace, 6
bind = SUPER CTRL, 7, movetoworkspace, 7
bind = SUPER CTRL, 8, movetoworkspace, 8
bind = SUPER CTRL, 9, movetoworkspace, 9
bind = SUPER CTRL, 0, movetoworkspace, 10

# Mouse
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

# Media
bind = , XF86AudioRaiseVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute,         exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86MonBrightnessUp,   exec, brightnessctl set 5%+
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Screenshot
bind = SUPER SHIFT, S, exec, bash -c 'f=~/Pictures/Screenshots/HYPR_$(date +%Y-%m-%d_%H%M%S).png && grimblast copysave area "$f" && notify-send "Screenshot" "Saved to $f"'
